from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.lib.styles import ParagraphStyle
import io, base64
from datetime import datetime

# Colors
BLUE         = colors.HexColor('#2563eb')
BLUE_DARK    = colors.HexColor('#1e40af')
BLUE_LIGHT   = colors.HexColor('#eff6ff')
BLUE_MID     = colors.HexColor('#bfdbfe')
RED          = colors.HexColor('#dc2626')
RED_LIGHT    = colors.HexColor('#fef2f2')
ORANGE       = colors.HexColor('#d97706')
ORANGE_LIGHT = colors.HexColor('#fffbeb')
GREEN        = colors.HexColor('#16a34a')
GREEN_LIGHT  = colors.HexColor('#f0fdf4')
SLATE_700    = colors.HexColor('#334155')
SLATE_500    = colors.HexColor('#64748b')
SLATE_300    = colors.HexColor('#cbd5e1')
SLATE_100    = colors.HexColor('#f1f5f9')
SLATE_50     = colors.HexColor('#f8fafc')
WHITE        = colors.white

# Global unique style counter
_sc = [0]

def mkstyle(size=9, color='#334155', bold=False, italic=False, align=TA_LEFT):
    _sc[0] += 1
    fn = 'Helvetica-Bold' if bold else ('Helvetica-Oblique' if italic else 'Helvetica')
    return ParagraphStyle(
        f'_s{_sc[0]}',
        fontSize=size,
        textColor=colors.HexColor(color),
        fontName=fn,
        alignment=align,
        leading=size * 1.5,
        spaceAfter=0,
        spaceBefore=0,
        wordWrap='CJK',
    )

def T(text, size=9, color='#334155', bold=False, italic=False, align=TA_LEFT):
    # Convert any non-ASCII or problematic characters
    text = str(text).replace('!', '!').replace('>', '>').replace('<', '<')
    return Paragraph(text, mkstyle(size, color, bold, italic, align))

def mktable(rows, widths, extra_styles=None):
    t = Table(rows, colWidths=widths, repeatRows=0)
    ts = [
        ('TOPPADDING',    (0,0), (-1,-1), 2.5*mm),
        ('BOTTOMPADDING', (0,0), (-1,-1), 2.5*mm),
        ('LEFTPADDING',   (0,0), (-1,-1), 3*mm),
        ('RIGHTPADDING',  (0,0), (-1,-1), 3*mm),
        ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
        ('GRID',          (0,0), (-1,-1), 0.3, SLATE_300),
        ('BACKGROUND',    (0,0), (-1,0),  SLATE_100),
    ]
    if extra_styles:
        ts.extend(extra_styles)
    t.setStyle(TableStyle(ts))
    return t

def shdr(title, bg=SLATE_700):
    t = Table([[T(title, size=9, color='#ffffff', bold=True)]], colWidths=[175*mm])
    t.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,-1), bg),
        ('LEFTPADDING',   (0,0), (-1,-1), 4*mm),
        ('RIGHTPADDING',  (0,0), (-1,-1), 4*mm),
        ('TOPPADDING',    (0,0), (-1,-1), 2*mm),
        ('BOTTOMPADDING', (0,0), (-1,-1), 2*mm),
        ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
    ]))
    return t

def risk_color(level):
    return {
        'high':   RED.hexval(),
        'medium': ORANGE.hexval(),
        'low':    GREEN.hexval(),
    }.get(level, SLATE_500.hexval())

def risk_bg(level):
    return {
        'high':   RED_LIGHT,
        'medium': ORANGE_LIGHT,
        'low':    GREEN_LIGHT,
    }.get(level, SLATE_50)

def vstatus(val, mn, mx):
    if val is None: return '—', '#64748b'
    return ('Normal', '#16a34a') if mn <= val <= mx else ('Abnormal', '#dc2626')

def adherence_bar(rate):
    f = int(rate * 20)
    bar = '=' * f + '-' * (20 - f)
    return f"{bar}  {int(rate*100)}%"

def generate_weekly_report_pdf(report_data):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        rightMargin=15*mm, leftMargin=15*mm,
        topMargin=15*mm, bottomMargin=15*mm
    )
    story = []

    # Cover header
    hdr = Table([[
        T("FamilyHealth Portal", size=15, color='#ffffff', bold=True),
        T(f"{report_data.get('family_name','')}\nWeek: {report_data.get('week_start','')} - {report_data.get('week_end','')}\nGenerated: {report_data.get('generated_at','')}",
          size=8, color='#bfdbfe', align=TA_RIGHT),
    ]], colWidths=[110*mm, 65*mm])
    hdr.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,-1), BLUE_DARK),
        ('LEFTPADDING',   (0,0), (-1,-1), 6*mm),
        ('RIGHTPADDING',  (0,0), (-1,-1), 6*mm),
        ('TOPPADDING',    (0,0), (-1,-1), 5*mm),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5*mm),
        ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story += [hdr, Spacer(1, 4*mm)]

    # Info pill
    n = len(report_data.get('members', []))
    pill = Table([[
        T(f"This report covers {n} family member{'s' if n!=1 else ''}. "
          f"Risk levels generated by XGBoost ML models trained on 470,000+ records.",
          size=8, color='#1e40af')
    ]], colWidths=[175*mm])
    pill.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,-1), BLUE_LIGHT),
        ('LEFTPADDING',   (0,0), (-1,-1), 4*mm),
        ('RIGHTPADDING',  (0,0), (-1,-1), 4*mm),
        ('TOPPADDING',    (0,0), (-1,-1), 3*mm),
        ('BOTTOMPADDING', (0,0), (-1,-1), 3*mm),
    ]))
    story += [pill, Spacer(1, 6*mm)]

    for idx, m in enumerate(report_data.get('members', [])):
        name  = m.get('name', 'Member')
        score = m.get('health_score', 0)
        grade = m.get('health_grade', 'N/A')
        stats = m.get('weekly_stats', {})
        risks = m.get('risk_assessment', {})
        facts = m.get('contributing_factors', [])
        pos   = m.get('positive_factors', [])
        summ  = m.get('gemini_summary', '')
        tip   = m.get('actionable_tip', '')
        motiv = m.get('closing_motivation', '')

        # Name bar
        nb = Table([[
            T(name, size=11, color='#ffffff', bold=True),
            T(f"Health Score: {score}/100  |  Grade: {grade}",
              size=9, color='#ffffff', bold=True, align=TA_RIGHT),
        ]], colWidths=[95*mm, 80*mm])
        nb.setStyle(TableStyle([
            ('BACKGROUND',    (0,0), (-1,-1), BLUE),
            ('LEFTPADDING',   (0,0), (-1,-1), 5*mm),
            ('RIGHTPADDING',  (0,0), (-1,-1), 5*mm),
            ('TOPPADDING',    (0,0), (-1,-1), 3*mm),
            ('BOTTOMPADDING', (0,0), (-1,-1), 3*mm),
            ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
        ]))
        story += [nb, Spacer(1, 3*mm)]

        # Vitals
        story += [shdr('Vitals This Week'), Spacer(1, 2*mm)]
        vrows = [[
            T('Metric',       size=8, color='#64748b', bold=True),
            T('Your Average', size=8, color='#64748b', bold=True, align=TA_CENTER),
            T('Normal Range', size=8, color='#64748b', bold=True, align=TA_CENTER),
            T('Status',       size=8, color='#64748b', bold=True, align=TA_CENTER),
        ]]
        rbgs = []
        for i, (label, val, mn, mx, unit) in enumerate([
            ('Blood Pressure (Systolic)',  stats.get('avg_systolic'),  90,  120, 'mmHg'),
            ('Blood Pressure (Diastolic)', stats.get('avg_diastolic'), 60,  80,  'mmHg'),
            ('Blood Sugar',                stats.get('avg_glucose'),   70,  100, 'mg/dL'),
            ('Pulse Rate',                 stats.get('avg_pulse'),     60,  100, 'bpm'),
        ]):
            disp = f"{float(val):.1f} {unit}" if val is not None else '—'
            st, sc = vstatus(val, mn, mx)
            vrows.append([
                T(label, size=9),
                T(disp,  size=9, bold=True, align=TA_CENTER),
                T(f"{mn}-{mx} {unit}", size=9, color='#64748b', align=TA_CENTER),
                T(st,    size=9, color=sc, bold=True, align=TA_CENTER),
            ])
            rbgs.append(WHITE if i%2==0 else SLATE_50)

        vt = Table(vrows, colWidths=[68*mm, 38*mm, 38*mm, 31*mm])
        vts = [
            ('BACKGROUND',    (0,0), (-1,0),  SLATE_100),
            ('TOPPADDING',    (0,0), (-1,-1), 2.5*mm),
            ('BOTTOMPADDING', (0,0), (-1,-1), 2.5*mm),
            ('LEFTPADDING',   (0,0), (-1,-1), 3*mm),
            ('RIGHTPADDING',  (0,0), (-1,-1), 3*mm),
            ('GRID',          (0,0), (-1,-1), 0.3, SLATE_300),
            ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
        ]
        for i, bg in enumerate(rbgs):
            vts.append(('BACKGROUND', (0,i+1), (-1,i+1), bg))
        vt.setStyle(TableStyle(vts))
        story += [vt, Spacer(1, 4*mm)]

        # Medication adherence
        story += [shdr('Medication Adherence'), Spacer(1, 2*mm)]
        adh = stats.get('adherence_rate', 0)
        tak = stats.get('doses_taken', 0)
        mis = stats.get('doses_missed', 0)
        tot = stats.get('doses_total', 0)
        ac  = '#16a34a' if adh>=0.8 else ('#d97706' if adh>=0.6 else '#dc2626')
        abg = GREEN_LIGHT if adh>=0.8 else (ORANGE_LIGHT if adh>=0.6 else RED_LIGHT)
        
        bar_text = adherence_bar(adh)
        # Fixed: Use a simple string and avoid complex table nesting
        at = Table([[bar_text + f"  |  {tak} of {tot} doses taken  |  {mis} missed"]], colWidths=[175*mm])
        at.setStyle(TableStyle([
            ('BACKGROUND',    (0,0), (-1,-1), abg),
            ('LEFTPADDING',   (0,0), (-1,-1), 4*mm),
            ('RIGHTPADDING',  (0,0), (-1,-1), 4*mm),
            ('TOPPADDING',    (0,0), (-1,-1), 3*mm),
            ('BOTTOMPADDING', (0,0), (-1,-1), 3*mm),
            ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
            ('FONT',          (0,0), (-1,-1), 'Helvetica', 9),
        ]))
        story += [at, Spacer(1, 4*mm)]

        # Risk assessment
        story += [shdr('Risk Assessment (ML Model)'), Spacer(1, 2*mm)]
        rrows = [[
            T('Condition',  size=8, color='#64748b', bold=True),
            T('Risk Level', size=8, color='#64748b', bold=True, align=TA_CENTER),
            T('Confidence', size=8, color='#64748b', bold=True, align=TA_CENTER),
            T('Key Driver', size=8, color='#64748b', bold=True),
        ]]
        rrbgs = []
        for i, rname in enumerate(['diabetes', 'hypertension', 'cardiovascular']):
            r     = risks.get(rname, {})
            level = r.get('risk_level', 'low')
            conf  = r.get('confidence', 0)
            driv  = str(r.get('key_driver', ''))[:55]
            rc    = risk_color(level)
            rrows.append([
                T(rname.capitalize(), size=9),
                T(level.upper(), size=9, color=rc, bold=True, align=TA_CENTER),
                T(f"{int(conf*100)}%", size=9, color='#64748b', align=TA_CENTER),
                T(driv, size=8, color='#64748b'),
            ])
            rrbgs.append(WHITE if i%2==0 else SLATE_50)

        rt = Table(rrows, colWidths=[35*mm, 30*mm, 25*mm, 85*mm])
        rts = [
            ('BACKGROUND',    (0,0), (-1,0),  SLATE_100),
            ('TOPPADDING',    (0,0), (-1,-1), 2.5*mm),
            ('BOTTOMPADDING', (0,0), (-1,-1), 2.5*mm),
            ('LEFTPADDING',   (0,0), (-1,-1), 3*mm),
            ('RIGHTPADDING',  (0,0), (-1,-1), 3*mm),
            ('GRID',          (0,0), (-1,-1), 0.3, SLATE_300),
            ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
        ]
        for i, bg in enumerate(rrbgs):
            rts.append(('BACKGROUND', (0,i+1), (-1,i+1), bg))
        rt.setStyle(TableStyle(rts))
        story += [rt, Spacer(1, 4*mm)]

        # Contributing factors
        if facts or pos:
            story += [shdr("What's Driving These Results"), Spacer(1, 2*mm)]
            # Fixed: Use simple strings instead of Paragraph objects
            ftexts = []
            for f in facts:
                ftexts.append(f"⚠ {f}")
            for p in pos:
                ftexts.append(f"✓ {p}")
            
            if ftexts:
                ft_text = "\n".join(ftexts)
                ft = Table([[T(ft_text, size=9)]], colWidths=[175*mm])
                ft.setStyle(TableStyle([
                    ('VALIGN',        (0,0), (-1,-1), 'TOP'),
                    ('LEFTPADDING',   (0,0), (-1,-1), 4*mm),
                    ('RIGHTPADDING',  (0,0), (-1,-1), 4*mm),
                    ('TOPPADDING',    (0,0), (-1,-1), 2*mm),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 2*mm),
                    ('BACKGROUND',    (0,0), (-1,-1), SLATE_50),
                ]))
                story += [ft, Spacer(1, 4*mm)]

        # AI summary
        if summ:
            story += [shdr('AI Health Summary', BLUE), Spacer(1, 2*mm)]
            sb = Table([[T(summ, size=9, color='#1e3a8a')]], colWidths=[175*mm])
            sb.setStyle(TableStyle([
                ('BACKGROUND',    (0,0), (-1,-1), BLUE_LIGHT),
                ('LEFTPADDING',   (0,0), (-1,-1), 5*mm),
                ('RIGHTPADDING',  (0,0), (-1,-1), 5*mm),
                ('TOPPADDING',    (0,0), (-1,-1), 4*mm),
                ('BOTTOMPADDING', (0,0), (-1,-1), 4*mm),
            ]))
            story += [sb, Spacer(1, 3*mm)]

        # Tip - Fixed: Remove nested table and use simple paragraph
        if tip:
            tip_text = f"💡 This Week's Tip: {tip}"
            tb = Table([[T(tip_text, size=9, color='#92400e')]], colWidths=[175*mm])
            tb.setStyle(TableStyle([
                ('BACKGROUND',    (0,0), (-1,-1), ORANGE_LIGHT),
                ('LEFTPADDING',   (0,0), (-1,-1), 4*mm),
                ('RIGHTPADDING',  (0,0), (-1,-1), 4*mm),
                ('TOPPADDING',    (0,0), (-1,-1), 3*mm),
                ('BOTTOMPADDING', (0,0), (-1,-1), 3*mm),
                ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
            ]))
            story += [tb, Spacer(1, 3*mm)]

        # Motivation
        if motiv:
            mb = Table([[T(motiv, size=9, color='#166534', italic=True, align=TA_CENTER)]],
                       colWidths=[175*mm])
            mb.setStyle(TableStyle([
                ('BACKGROUND',    (0,0), (-1,-1), GREEN_LIGHT),
                ('LEFTPADDING',   (0,0), (-1,-1), 5*mm),
                ('RIGHTPADDING',  (0,0), (-1,-1), 5*mm),
                ('TOPPADDING',    (0,0), (-1,-1), 3*mm),
                ('BOTTOMPADDING', (0,0), (-1,-1), 3*mm),
            ]))
            story.append(mb)

        story.append(Spacer(1, 5*mm))
        if idx < len(report_data.get('members', [])) - 1:
            story.append(HRFlowable(width="100%", thickness=1.5, color=BLUE_MID, spaceAfter=5*mm))

    # Footer
    story.append(Spacer(1, 4*mm))
    footer = Table([[
        T('Generated by FamilyHealth Portal  |  Powered by XGBoost ML Models  |  '
          'For informational purposes only  |  Always consult your healthcare provider',
          size=7, color='#94a3b8', align=TA_CENTER)
    ]], colWidths=[175*mm])
    footer.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,-1), SLATE_50),
        ('TOPPADDING',    (0,0), (-1,-1), 3*mm),
        ('BOTTOMPADDING', (0,0), (-1,-1), 3*mm),
        ('LEFTPADDING',   (0,0), (-1,-1), 4*mm),
    ]))
    story.append(footer)

    doc.build(story)
    buf.seek(0)
    return base64.b64encode(buf.read()).decode('utf-8')


if __name__ == '__main__':
    test_data = {
        "family_name": "Agarwal Family",
        "week_start":  "Jun 8, 2026",
        "week_end":    "Jun 14, 2026",
        "generated_at": datetime.now().strftime("%b %d, %Y %I:%M %p"),
        "members": [
            {
                "name": "Hardik Agarwal",
                "health_score": 81.0, "health_grade": "B",
                "weekly_stats": {
                    "avg_systolic": 138, "avg_diastolic": 88,
                    "avg_glucose": 142, "avg_pulse": 82,
                    "adherence_rate": 0.73,
                    "doses_taken": 18, "doses_missed": 4, "doses_total": 22,
                    "bp_variability": 12.3, "sugar_variability": 18.5
                },
                "risk_assessment": {
                    "diabetes":       {"risk_level":"high",   "confidence":0.989, "key_driver":"Elevated blood sugar 142 mg/dL"},
                    "hypertension":   {"risk_level":"medium", "confidence":0.962, "key_driver":"Systolic BP above 130 mmHg"},
                    "cardiovascular": {"risk_level":"high",   "confidence":0.85,  "key_driver":"Combined BP and glucose elevation"}
                },
                "contributing_factors": [
                    "Elevated systolic BP 138 mmHg",
                    "High blood sugar 142 mg/dL",
                    "Medication adherence below target 73%",
                    "BMI indicates overweight 27.4"
                ],
                "positive_factors": ["Pulse rate normal 82 bpm", "Diastolic BP close to normal"],
                "gemini_summary": "Hardik, this week showed some areas that need attention alongside real positives. Your blood pressure and sugar readings were slightly elevated. Taking your medications more consistently will help bring these numbers toward the healthy range.",
                "actionable_tip": "Try a 20-minute walk after dinner to lower post-meal blood sugar levels.",
                "closing_motivation": "Small consistent steps today build a healthier tomorrow. You are on the right track!"
            },
            {
                "name": "Priya Agarwal",
                "health_score": 91.0, "health_grade": "A",
                "weekly_stats": {
                    "avg_systolic": 112, "avg_diastolic": 74,
                    "avg_glucose": 88, "avg_pulse": 70,
                    "adherence_rate": 0.95,
                    "doses_taken": 20, "doses_missed": 1, "doses_total": 21,
                    "bp_variability": 4.2, "sugar_variability": 6.1
                },
                "risk_assessment": {
                    "diabetes":       {"risk_level":"low", "confidence":0.96, "key_driver":"Blood sugar well within range"},
                    "hypertension":   {"risk_level":"low", "confidence":0.98, "key_driver":"BP consistently normal"},
                    "cardiovascular": {"risk_level":"low", "confidence":0.92, "key_driver":"All indicators healthy"}
                },
                "contributing_factors": [],
                "positive_factors": [
                    "Blood pressure excellent 112/74 mmHg",
                    "Blood sugar normal 88 mg/dL",
                    "Medication adherence excellent 95%",
                    "Pulse rate normal 70 bpm"
                ],
                "gemini_summary": "Priya, you had an excellent week! All your health indicators are within the healthy range and your medication adherence is outstanding. Keep up the great work.",
                "actionable_tip": "Keep maintaining your current routine. Consistency is the key to long-term health.",
                "closing_motivation": "Excellent work this week! Your dedication to your health is truly inspiring."
            }
        ]
    }

    print("Generating test PDF...")
    pdf_b64 = generate_weekly_report_pdf(test_data)
    with open('test_report.pdf', 'wb') as f:
        f.write(base64.b64decode(pdf_b64))
    print(f"✅ Test PDF saved!")
    print(f"   Size: {len(base64.b64decode(pdf_b64))/1024:.1f} KB")